import { LearningPath } from "../types";

export const getDemoPath = (t: any): LearningPath => ({
  id: "demo-landing",
  name: t.demo_map_name,
  description: t.demo_map_desc,
  nodes: [
    {
      id: "node-1",
      title: t.demo_node_1_title,
      type: "article",
      description: t.demo_node_1_desc,
      source: "Sports Medicine Weekly",
      location: "Issue 42",
      status: "completed",
      progress: 100,
      connections: ["node-2", "node-3"],
    },
    {
      id: "node-2",
      title: t.demo_node_2_title,
      type: "chapter",
      description: t.demo_node_2_desc,
      source: "Human Anatomy — Tortora",
      location: "Chapter 10",
      status: "completed",
      progress: 100,
      connections: ["node-4"],
    },
    {
      id: "node-3",
      title: t.demo_node_3_title,
      type: "video",
      description: t.demo_node_3_desc,
      source: "Aspetar Sports Medicine Journal",
      location: "Vol. 12",
      status: "in-progress",
      progress: 45,
      connections: ["node-4", "node-5"],
    },
    {
      id: "node-4",
      title: t.demo_node_4_title,
      type: "course",
      description: t.demo_node_4_desc,
      source: "NSCA Essentials of Strength Training",
      location: "Part III",
      status: "unexplored",
      progress: 0,
      connections: ["node-6"],
    },
    {
      id: "node-5",
      title: t.demo_node_5_title,
      type: "book",
      description: t.demo_node_5_desc,
      source: "Exercise Physiology — McArdle",
      location: "Chapter 7",
      status: "unexplored",
      progress: 0,
      connections: ["node-6"],
    },
    {
      id: "node-6",
      title: t.demo_node_6_title,
      type: "article",
      description: t.demo_node_6_desc,
      source: "Journal of Sports Sciences",
      location: "2024 Edition",
      status: "locked",
      progress: 0,
      connections: [],
    },
  ],
});
